name: Run tests

on: 
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  #run_linter:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master    # checkout master branch
      - uses: actions/setup-python@v1    # setup python
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r deepfake-detector-ml/requirements.txt
      - name: Run tests
        run: pytest